---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: debug-server
    image: kdrag0n/drone-ssh-debug:latest
    detach: true

    settings:
      authorized_keys:
        # authorized_keys for SSH debug server in ssh_authorized_keys secret
        from_secret: ssh_authorized_keys

    when:
      event:
        exclude:
          - pull_request
          - tag

  - name: build
    image: kdrag0n/debian-llvm-build:buster

    commands:
      - .drone/build.sh

    when:
      event:
        exclude:
          - tag

  - name: github
    image: kdrag0n/debian-llvm-build:buster

    environment:
      # GitHub personal access token ()
      # Generate at https://github.com/settings/tokens/new
      # Scopes required: repo:public_repo
      GITHUB_TOKEN:
        from_secret: github_token

      # Time limit
      TIMEOUT: 15m

    commands:
      - timeout $TIMEOUT .drone/github.sh

    when:
      event:
        exclude:
          - pull_request
          - tag

  - name: telegram
    image: kdrag0n/debian-llvm-build:buster

    environment:
      # Telegram chat ID
      # This is either the numerical ID or "@chat_username" (must be quoted)
      TG_CHAT_ID: "@proton_clang_ci"

      # Telegram bot token (stored in tg_bot_token secret)
      TG_BOT_TOKEN:
        from_secret: tg_bot_token

      # Time limit
      TIMEOUT: 2m

    commands:
      - timeout $TIMEOUT .drone/telegram.sh

    when:
      status:
        - success
        - failure
      event:
        exclude:
          - pull_request
          - tag

  - name: debug-wait
    image: kdrag0n/debian-llvm-build:buster

    environment:
      # Amount of time to wait for debugging
      # This is intended to serve as a brief preliminary analysis, not a
      # full-fledged post-mortem analysis session
      DEBUG_TIME: 3m

    commands:
      - sleep $DEBUG_TIME

    when:
      status:
        - failure
      event:
        exclude:
          - pull_request
          - tag
